create table USERS (
    USERNAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PHOTO_URL VARCHAR(150),
    PASSWORD VARCHAR(150),
    PRIMARY KEY(USERNAME)
);

create table CONVERSATION (
    ID_KEY VARCHAR(150) NOT NULL,
    MAIN_USER VARCHAR(150) NOT NULL,
    WITH_USER VARCHAR(150) NOT NULL,
    PRIMARY KEY(ID_KEY, MAIN_USER)
);

create table ROLES (
    ID INTEGER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

create table USER_ROLES (
    USER_ID VARCHAR(150) NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    PRIMARY KEY(USER_ID, ROLE_ID)
);